// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RestAPITests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SearchTests")]
    public partial class SearchTestsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SearchTests.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SearchTests", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SearchByTextInUsaBdd")]
        [NUnit.Framework.CategoryAttribute("SearchTestsSuit")]
        [NUnit.Framework.CategoryAttribute("Client")]
        public virtual void SearchByTextInUsaBdd()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SearchByTextInUsaBdd", new string[] {
                        "SearchTestsSuit",
                        "Client"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Abbr",
                        "Area",
                        "Capital",
                        "Country",
                        "LargestCity",
                        "Name"});
            table1.AddRow(new string[] {
                        "WA",
                        "184661SKM",
                        "Olympia",
                        "USA",
                        "Seattle",
                        "Washington"});
#line 6
 testRunner.Given("I have a CountryInfo object", ((string)(null)), table1, "Given ");
#line 9
 testRunner.And("I call service \'/state/search/{country}?text={state}\' with parameters \'USA\' and \'" +
                    "wash\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When("I get response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("the response is equal to CountryInfo object", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("SearchByTextInINDBdd")]
        [NUnit.Framework.CategoryAttribute("SearchTestsSuit")]
        [NUnit.Framework.CategoryAttribute("Client")]
        public virtual void SearchByTextInINDBdd()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("SearchByTextInINDBdd", new string[] {
                        "SearchTestsSuit",
                        "Client"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Abbr",
                        "Area",
                        "Capital",
                        "Country",
                        "LargestCity",
                        "Name"});
            table2.AddRow(new string[] {
                        "AP",
                        "49506799SKM",
                        "Hyderabad Amaravati",
                        "IND",
                        "Hyderabad Amaravati",
                        "Andhra Pradesh"});
#line 16
 testRunner.Given("I have a CountryInfo object", ((string)(null)), table2, "Given ");
#line 19
 testRunner.And("I call service \'/state/search/{country}?text={state}\' with parameters \'IND\' and \'" +
                    "pradesh\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.When("I get response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.Then("the response is equal to CountryInfo object", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
